name: "actionlint"

on:
  workflow_dispatch: # allows manual triggering
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  merge_group:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - uses: nixos/nix-installer-action@6b8548fe06acfb0155a50ab5d561accb215764cc # main
    - name: "actionlint"
      run: nix run -Lv --refresh --inputs-from .# nixpkgs#actionlint -- --ignore SC2002
