name: "actionlint"

on:
  workflow_dispatch: # allows manual triggering
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  merge_group:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - uses: nixos/nix-installer-action@6b8548fe06acfb0155a50ab5d561accb215764cc # main
    - name: "actionlint"
      run: nix run -Lv --refresh --inputs-from .# nixpkgs#actionlint -- --ignore SC2002
