name: "ci"
on:
  workflow_dispatch: # allows manual triggering
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
  merge_group:
jobs:
  dependencies:
    runs-on: ubuntu-latest
    environment: cachix
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: kenji
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: DeterminateSystems/magic-nix-cache-action@v13
        with:
          diagnostic-endpoint: ""
      - name: "build dependencies"
        run: nix build .#checks.x86_64-linux.cargoArtifacts -Lvv --no-update-lock-file
  formatting:
    runs-on: ubuntu-latest
    environment: cachix
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: kenji
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: DeterminateSystems/magic-nix-cache-action@v13
        with:
          diagnostic-endpoint: ""
      - name: "check formatting"
        run: nix build .#checks.x86_64-linux.treefmt -Lvv --no-update-lock-file
  tests:
    runs-on: ubuntu-latest
    environment: cachix
    needs: ['formatting', 'dependencies']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: kenji
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: DeterminateSystems/magic-nix-cache-action@v13
        with:
          diagnostic-endpoint: ""
      - name: "run tests"
        run: nix build .#checks.x86_64-linux.cargoTest -Lvv --no-update-lock-file
  docs:
    runs-on: ubuntu-latest
    environment: cachix
    needs: ['formatting', 'dependencies']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: kenji
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: DeterminateSystems/magic-nix-cache-action@v13
        with:
          diagnostic-endpoint: ""
      - name: "build cargo documentation"
        run: nix build .#checks.x86_64-linux.cargoDoc -Lvv --no-update-lock-file
  clippy:
    runs-on: ubuntu-latest
    environment: cachix
    needs: ['formatting', 'dependencies']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: kenji
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: DeterminateSystems/magic-nix-cache-action@v13
        with:
          diagnostic-endpoint: ""
      - name: "run cargo clippy"
        run: nix build .#checks.x86_64-linux.cargoClippy -Lvv --no-update-lock-file
  sizelint:
    runs-on: ubuntu-latest
    environment: cachix
    needs: ['formatting', 'dependencies' ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: kenji
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: DeterminateSystems/magic-nix-cache-action@v13
        with:
          diagnostic-endpoint: ""
      - name: "build sizelint"
        run: nix build .#packages.x86_64-linux.sizelint -Lvv --no-update-lock-file
  devshells:
    runs-on: ubuntu-latest
    environment: cachix
    needs: ['formatting']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: kenji
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: DeterminateSystems/magic-nix-cache-action@v13
        with:
          diagnostic-endpoint: ""
      - name: "build devshells"
        run: nix develop .#devShells.x86_64-linux.full -Lvv --no-update-lock-file
